// src/config/mockData.js
export const MOCK_API_RESPONSES = {
    '/payment/listIncomingTrans': {
        "content": [
            {
                "seqNo": 311825,
                "benId": "970436",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "CKVCBS009C038955",
                "toAccountType": "ACC",
                "localDate": "0330",
                "settlementDate": "0330",
                "localTime": "164807",
                "amount": "20260330",
                "traceNo": "900474",
                "refCode": "608916900474",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "04",
                "procCode": "912020",
                "transContent": "P2PNop tien009C038955NGUYEN HOANG LUAN01",
                "f120": "NGUYEN HOANG LUAN",
                "transDate": "2026-03-30T09:48:07Z",
                "transRef": "6089BNPMA2CGS7VK",
                "returnedAmount": 150000,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "NGUYEN HOANG LUAN",
                "transactionType": "IBFT"
            },
            {
                "seqNo": 311169,
                "benId": "555666",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "TOANTDBIDC",
                "toAccountType": "ACC",
                "localDate": "0327",
                "settlementDate": "0327",
                "localTime": "174044",
                "amount": "1000000",
                "traceNo": "641326",
                "refCode": "608617641326",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "99",
                "procCode": "502020",
                "transContent": "Thanh toan hoa don 0IHIUPTE",
                "f120": "Cty TNHH TDT",
                "transDate": "2026-03-27T10:40:44Z",
                "transRef": "6086BNPMA2CGJ77W",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "Cty TNHH TDT",
                "transactionType": "PAYMENT"
            },
            {
                "seqNo": 311156,
                "benId": "555666",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "TOANTDBIDC",
                "toAccountType": "ACC",
                "localDate": "0327",
                "settlementDate": "0327",
                "localTime": "172610",
                "amount": "1000000",
                "traceNo": "234816",
                "refCode": "608617234816",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "99",
                "procCode": "502020",
                "transContent": "Thanh toan hoa don 0IHIUPTE",
                "f120": "Cty TNHH TDT",
                "transDate": "2026-03-27T10:26:10Z",
                "transRef": "6086BNPMA2CGJEQM",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "Cty TNHH TDT",
                "transactionType": "PAYMENT"
            },
            {
                "seqNo": 311153,
                "benId": "555666",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "TOANTDBIDC",
                "toAccountType": "ACC",
                "localDate": "0327",
                "settlementDate": "0327",
                "localTime": "171454",
                "amount": "11110",
                "traceNo": "914809",
                "refCode": "608617914809",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "99",
                "procCode": "502020",
                "transContent": "chuyen tien",
                "f120": "Cty TNHH TDT",
                "transDate": "2026-03-27T10:14:54Z",
                "transRef": "6086BNPMA2CGFSYE",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "Cty TNHH TDT",
                "transactionType": "PAYMENT"
            },
            {
                "seqNo": 310663,
                "benId": "970419",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "CH0WCHOW",
                "toAccountType": "ACC",
                "localDate": "0326",
                "settlementDate": "0326",
                "localTime": "112115",
                "amount": "111110",
                "traceNo": "575087",
                "refCode": "608511575087",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "04",
                "procCode": "912020",
                "transContent": "ez",
                "f120": "NGUYEN THI HANG",
                "transDate": "2026-03-26T04:21:15Z",
                "transRef": "6085BNPMA2CGLHGQ",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "NGUYEN THI HANG",
                "transactionType": "IBFT"
            },
            {
                "seqNo": 310522,
                "benId": "970425",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "0129837294",
                "toAccountType": "ACC",
                "localDate": "0325",
                "settlementDate": "0325",
                "localTime": "175427",
                "amount": "25000",
                "traceNo": "070046",
                "refCode": "608417070046",
                "respcode": "91",
                "benRespcode": "91",
                "f60": "04",
                "procCode": "912020",
                "transContent": "test ck",
                "transDate": "2026-03-25T10:54:27Z",
                "transRef": "INPLIBFTA2CG21PW",
                "returnedAmount": 0,
                "settlementStatus": "RJCT",
                "senderName": "Tran Duy Toan",
                "transactionType": "IBFT"
            }
        ],
        "pageable": {
            "sort": {
                "sorted": true,
                "empty": false,
                "unsorted": false
            },
            "pageNumber": 0,
            "pageSize": 30,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "last": true,
        "totalPages": 1,
        "totalElements": 6,
        "size": 30,
        "number": 0,
        "sort": {
            "sorted": true,
            "empty": false,
            "unsorted": false
        },
        "first": true,
        "numberOfElements": 6,
        "empty": false
    },
    '/payment/listTrans': {
        "content": [
            {
                "seqNo": 311825,
                "benId": "970436",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "CKVCBS009C038955",
                "toAccountType": "ACC",
                "localDate": "0330",
                "settlementDate": "0330",
                "localTime": "164807",
                "amount": "20260330",
                "traceNo": "900474",
                "refCode": "608916900474",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "04",
                "procCode": "912020",
                "transContent": "P2PNop tien009C038955NGUYEN HOANG LUAN01",
                "f120": "NGUYEN HOANG LUAN",
                "transDate": "2026-03-30T09:48:07Z",
                "transRef": "6089BNPMA2CGS7VK",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "NGUYEN HOANG LUAN",
                "transactionType": "IBFT"
            },
            {
                "seqNo": 311169,
                "benId": "555666",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "TOANTDBIDC",
                "toAccountType": "ACC",
                "localDate": "0327",
                "settlementDate": "0327",
                "localTime": "174044",
                "amount": "1000000",
                "traceNo": "641326",
                "refCode": "608617641326",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "99",
                "procCode": "502020",
                "transContent": "Thanh toan hoa don 0IHIUPTE",
                "f120": "Cty TNHH TDT",
                "transDate": "2026-03-27T10:40:44Z",
                "transRef": "6086BNPMA2CGJ77W",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "Cty TNHH TDT",
                "transactionType": "PAYMENT"
            },
            {
                "seqNo": 311156,
                "benId": "555666",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "TOANTDBIDC",
                "toAccountType": "ACC",
                "localDate": "0327",
                "settlementDate": "0327",
                "localTime": "172610",
                "amount": "1000000",
                "traceNo": "234816",
                "refCode": "608617234816",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "99",
                "procCode": "502020",
                "transContent": "Thanh toan hoa don 0IHIUPTE",
                "f120": "Cty TNHH TDT",
                "transDate": "2026-03-27T10:26:10Z",
                "transRef": "6086BNPMA2CGJEQM",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "Cty TNHH TDT",
                "transactionType": "PAYMENT"
            },
            {
                "seqNo": 311153,
                "benId": "555666",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "TOANTDBIDC",
                "toAccountType": "ACC",
                "localDate": "0327",
                "settlementDate": "0327",
                "localTime": "171454",
                "amount": "11110",
                "traceNo": "914809",
                "refCode": "608617914809",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "99",
                "procCode": "502020",
                "transContent": "chuyen tien",
                "f120": "Cty TNHH TDT",
                "transDate": "2026-03-27T10:14:54Z",
                "transRef": "6086BNPMA2CGFSYE",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "Cty TNHH TDT",
                "transactionType": "PAYMENT"
            },
            {
                "seqNo": 310663,
                "benId": "970419",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "CH0WCHOW",
                "toAccountType": "ACC",
                "localDate": "0326",
                "settlementDate": "0326",
                "localTime": "112115",
                "amount": "111110",
                "traceNo": "575087",
                "refCode": "608511575087",
                "respcode": "00",
                "benRespcode": "00",
                "f60": "04",
                "procCode": "912020",
                "transContent": "ez",
                "f120": "NGUYEN THI HANG",
                "transDate": "2026-03-26T04:21:15Z",
                "transRef": "6085BNPMA2CGLHGQ",
                "returnedAmount": 0,
                "settlementStatus": "ACSP",
                "senderName": "Tran Duy Toan",
                "receiverName": "NGUYEN THI HANG",
                "transactionType": "IBFT"
            },
            {
                "seqNo": 310522,
                "benId": "970425",
                "bankId": "963666",
                "fromAccount": "NAPAS00PAY",
                "toAccount": "0129837294",
                "toAccountType": "ACC",
                "localDate": "0325",
                "settlementDate": "0325",
                "localTime": "175427",
                "amount": "25000",
                "traceNo": "070046",
                "refCode": "608417070046",
                "respcode": "91",
                "benRespcode": "91",
                "f60": "04",
                "procCode": "912020",
                "transContent": "test ck",
                "transDate": "2026-03-25T10:54:27Z",
                "transRef": "INPLIBFTA2CG21PW",
                "returnedAmount": 0,
                "settlementStatus": "RJCT",
                "senderName": "Tran Duy Toan",
                "transactionType": "IBFT"
            }
        ],
        "pageable": {
            "sort": {
                "sorted": true,
                "empty": false,
                "unsorted": false
            },
            "pageNumber": 0,
            "pageSize": 30,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "last": true,
        "totalPages": 1,
        "totalElements": 6,
        "size": 30,
        "number": 0,
        "sort": {
            "sorted": true,
            "empty": false,
            "unsorted": false
        },
        "first": true,
        "numberOfElements": 6,
        "empty": false
    },
    '/api/v1/disputes/incoming': {
        content: [
            { disputeId: 'DS-001', f63: 'NAPAS_QR_01', reason: 'Giao dịch trùng', status: 'OPEN' },
            { disputeId: 'DS-002', f63: 'VIETQR_02', reason: 'Sai số tiền', status: 'PENDING' }
        ],
        totalPages: 1,
        totalElements: 2,
        size: 10,
        number: 0
    },
    '/api/v1/logs/transactions': {
        content: [
            { timestamp: '2026-03-28 22:00:01', action: 'INIT_PAYMENT', f63: 'TX_999' },
            { timestamp: '2026-03-28 22:01:45', action: 'VERIFY_OTP', f63: 'TX_999' },
            { timestamp: '2026-03-28 22:02:10', action: 'SUCCESS', f63: 'TX_999' }
        ],
        totalPages: 10,
        totalElements: 100,
        size: 10,
        number: 0
    }
};